/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_UsbCamera */

#ifndef _Included_jni_UsbCamera
#define _Included_jni_UsbCamera
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_topotek_topotekmodule_cameraView_AutoPreviewView_usbCamera
  (JNIEnv *, jobject, jstring, jint, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
